# Generated by Django 4.2.2 on 2023-06-18 03:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingpersons',
            name='date_missing',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 6, 18, 3, 18, 53, 970144)),
        ),
    ]
